name: Managed Build and Push Image to Registry #
description: Builds and pushes an image to a managed registry
inputs:
  registry-repo-name:
    description: Name of the registry repository to push images to (based on ECR). Defaults to the Git repository's name.
    required: false
    default: ${{ github.repository }}
  tag-versions:
    description: git tags to push, comma separated string such as `latest,v1.0.0`
    required: true
  docker-context:
    description: docker context. Passed to [docker build push action context input](https://github.com/docker/build-push-action#inputs). It should be relative to the root of the commit that triggered the action
    required: false
    default: './'
  docker-file:
    description: path to docker file relative to docker-context. Passed to [docker build push action file input](https://github.com/docker/build-push-action#inputs)
    required: false
    default: Dockerfile
  aws-access-key-id:
    description: AWS access key id
    required: true
  aws-secret-access-key:
    description: AWS secret access key
    required: true
runs:
  using: "composite"
  steps:
    - name: Build and push image to ECR
      uses: atomicfi-engineering/action-build-push-image-ecr@v1
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: us-east-1
        role-duration-seconds: 900
        role-to-assume: arn:aws:iam::892765726487:role/GithubActionsRole
        ecr-repository: ${{ inputs.registry-repo-name }}
        create-missing-repositories: false
        tag-versions: ${{ inputs.tag-versions }}
        docker-context: ${{ inputs.docker-context }}
        docker-file: ${{ inputs.docker-file }}
